"""
infrastructure/speech/tts/windows_system.py

Windows System TTS Provider.
Uses native System.Speech.Synthesis via PowerShell.
"""

from __future__ import annotations

import datetime
import logging
import subprocess
import tempfile
from pathlib import Path

from beta.interaction.voice.contracts import SpeechArtifact, TtsProvider, VoiceHint
from beta.infrastructure.character_assets.validation.security import compute_sha256

logger = logging.getLogger(__name__)


class WindowsSystemTtsProvider(TtsProvider):
    @property
    def provider_id(self) -> str:
        return "windows-system"

    def synthesize(self, text: str, hint: VoiceHint | None, output_path: Path) -> SpeechArtifact:
        """
        Synthesizes text using Windows System TTS.
        Writes the text to a temporary file, then calls a small PowerShell script to process it.
        This prevents command injection.
        """
        rate = 0
        volume = 100
        
        if hint:
            if hint.speaking_rate is not None:
                # SAPI rate is roughly -10 to 10
                rate = int(max(-10, min(10, (hint.speaking_rate - 1.0) * 10)))
            if hint.volume is not None:
                volume = int(max(0, min(100, hint.volume * 100)))

        # Create temporary text file for the input text to prevent command injection
        with tempfile.NamedTemporaryFile(mode="w", encoding="utf-8-sig", delete=False, suffix=".txt") as tf:
            tf.write(text)
            text_file_path = tf.name

        ps_script = f"""
Param(
    [string]$TextPath,
    [string]$OutputPath,
    [int]$Rate,
    [int]$Volume
)

Add-Type -AssemblyName System.Speech
$synth = New-Object System.Speech.Synthesis.SpeechSynthesizer
$synth.Rate = $Rate
$synth.Volume = $Volume

$text = Get-Content -Path $TextPath -Raw -Encoding UTF8

$synth.SetOutputToWaveFile($OutputPath)
$synth.Speak($text)
$synth.Dispose()
"""

        with tempfile.NamedTemporaryFile(mode="w", encoding="utf-8", delete=False, suffix=".ps1") as pf:
            pf.write(ps_script)
            script_path = pf.name

        try:
            output_path.parent.mkdir(parents=True, exist_ok=True)
            
            # Execute without shell=True
            result = subprocess.run(
                ["powershell.exe", "-NoProfile", "-ExecutionPolicy", "Bypass", "-File", script_path, 
                 "-TextPath", text_file_path, 
                 "-OutputPath", str(output_path), 
                 "-Rate", str(rate), 
                 "-Volume", str(volume)],
                capture_output=True,
                text=True,
                check=False,
                timeout=60
            )
            
            if result.returncode != 0:
                raise RuntimeError(f"PowerShell TTS failed: {result.stderr}")
                
            if not output_path.exists():
                raise FileNotFoundError("TTS completed but output file not found.")
                
            checksum = compute_sha256(output_path)
            size = output_path.stat().st_size
            
            return SpeechArtifact(
                path=output_path,
                format="wav",
                sample_rate=22050,  # SAPI5 default roughly
                channels=1,
                provider=self.provider_id,
                pipeline="system_tts",
                character_profile_id="unknown", # Filled by service
                generated_at=datetime.datetime.now(datetime.timezone.utc).isoformat(),
                size_bytes=size,
                checksum=checksum,
                provenance="Generated by WindowsSystemTtsProvider",
                warnings=[]
            )
            
        finally:
            # Cleanup temp files
            try:
                Path(text_file_path).unlink()
            except OSError:
                pass
            try:
                Path(script_path).unlink()
            except OSError:
                pass
